src/IndyFurConCore/Models/IStaffQuery.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IndyFurConCore.Web.Models;
using Microsoft.AspNetCore.Hosting;

namespace IndyFurConCore.Models {
	public interface IStaffQuery {
		StaffCollection GetStaff();
	}
}

src/IndyFurConCore/Models/JsonStaffQuery.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using IndyFurConCore.Web.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.FileProviders;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Newtonsoft.Json;

namespace IndyFurConCore.Models
{
	public class JsonStaffQuery : IStaffQuery {
		private readonly IHostingEnvironment mEnv;
		private readonly string mFilePath;
		private readonly IFileInfo mFileInfo;

		public JsonStaffQuery(IHostingEnvironment env) {
			mEnv = env;
			mFilePath = Path.Combine(mEnv.WebRootPath, "StaffExample.json");
			var provider = new PhysicalFileProvider(mEnv.WebRootPath);
			mFileInfo = provider.GetFileInfo("StaffExample.json");
		}

		public StaffCollection GetStaff() {
			string file;
			using (StreamReader stream = new StreamReader(mFileInfo.CreateReadStream())) {
				file = stream.ReadToEnd();
			}

			StaffCollection staff = JsonConvert.DeserializeObject<StaffCollection>(file);

			return staff;
		}
	}
}

src/IndyFurConCore/Models/RegistrationBenefit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IndyFurConCore.Models {
    public class RegistrationBenefit {
        public bool UseIcon { get; set; } = true;
        public string Icon { get; set; }
        public string Text { get; set; }

        public RegistrationBenefit(string icon, string text, bool useIcon = true) {
            Icon = icon;
            Text = text;
            UseIcon = useIcon;
        }
    }
}

src/IndyFurConCore/Models/Staff.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace IndyFurConCore.Web.Models {
	public class Staff {
        public int Id { get; set; }
        public string RealName { get; set; }

        private string mName;
        public string Name {
            get { return mName; }
            set {
                if (string.IsNullOrWhiteSpace(RealName)) {
                    mName = value;
                } else {
                    mName = $"{value} ({RealName})";
                }
            }
        }
		
		[EmailAddress]
		public string EmailAddress { get; set; }

        public string ImageUrl { get; set; }

        public string Title { get; set; }

        public string Bio { get; set; }
    }

    public class StaffCollection {
        public List<Staff> Board { get; set; }
        public List<Staff> Staff { get; set; }
    }
}

src/IndyFurConCore/Controllers/AboutController.cs
using System;
using System.Linq;
using IndyFurConCore.Models;
using IndyFurConCore.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace IndyFurCon.Web.Controllers {
    public class AboutController : Controller {
		private readonly IStaffQuery mStaffQuery;
		public AboutController(IStaffQuery staffQuery) {
			mStaffQuery = staffQuery;
		}
		
        public ActionResult Index() {
            return View();
        }

        public ActionResult Charity() {
            return View();
        }

		// No Models for staff here so we can edit on the server
		public ActionResult Staff() {
            StaffCollection staff = mStaffQuery.GetStaff();

            for (int i = 0; i < staff.Board.Count; i++) {
                staff.Board[i].Id = i;
            }

            for (int i = 0; i < staff.Staff.Count; i++) {
                staff.Staff[i].Id = i;
            }

            staff.Staff = staff.Staff.OrderBy(s => s.Name).ToList();

            return View(staff);
        }

	    public ActionResult Volunteer() {
		    return View();
	    }
    }
}

src/IndyFurConCore/Controllers/AttendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IndyFurConCore.Util;
using Microsoft.AspNetCore.Mvc;

namespace IndyFurConCore.Controllers {
	public class AttendController : Controller {
		private readonly IAppSettingsAccess mAppSettingsAccess;

		public AttendController(IAppSettingsAccess appSettingsAccess) {
			mAppSettingsAccess = appSettingsAccess;
		}

		public IActionResult Hotel() {
			ViewData["ApiKey"] = mAppSettingsAccess.GetSetting(Constants.AppSettings.ApiAccess.Google.ApiKey);
			return View();
		}

		public IActionResult Travel() {
			return View();
		}
        
        public IActionResult Programming() {
            return View();
        }

        public IActionResult DanceCompetition() {
            return View();
        }

		public IActionResult FloorWars() {
			return View();
		}
	}
}

src/IndyFurConCore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace IndyFurConCore.Controllers {
	public class HomeController : Controller {

		public ActionResult Index() {
			return View();
		}

        public ActionResult Register() {
            return View();
        }
    }
}

src/IndyFurConCore/Controllers/PoliciesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace IndyFurConCore.Controllers {
	public class PoliciesController : Controller {
		public IActionResult Index() {
			return View();
		}

		public IActionResult ConventionAndConduct() {
			return View();
		}

		public IActionResult MediaAndPress() {
			return View();
		}

		public IActionResult Privacy() {
			return View();
		}
	}
}

src/IndyFurConCore/Views/About/Staff.cshtml
@using IndyFurConCore.Web.Models;
@using IndyFurConCore.Util;
@using System.IO;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, IndyFurConCore
@model StaffCollection
@{
    ViewBag.Title = "Staff";
    const int RowColumnsBoard = 4;
    const int RowColumnsStaff = 5;
}

<style>
    .well h1,
    .well h2,
    .well h3,
    .well h4,
    .well h5,
    .well h6 {
        word-spacing: normal;
    }

    h1 > span {
        margin-top: 10px;
        font-size: 10px;
        top: -10px;
    }
</style>

<div class="container-body">
    <div class="jumbotron">

        <h1>Staff</h1>
        <p>
            To contact a staff member, click the green "Email" button on their profile card below.
            If the button is missing or you don't know who to contact, email your questions and comments
            to <mail-to email="chairman@indyfurcon.com" class="icon-email"></mail-to>
            and we'll get them to the right staff who will contact you soon.
        </p>
        <p>
            Would you like to work for iFC2017? If you have any skill set you think would be valuable,
            send us a run down on who you are, what experience you have, and what you'd like to do. We are always
            on the lookout for hard-working people who want to make iFC the best we can make it! Email
            <mail-to email="volunteer@indyfurcon.com"></mail-to> your resume today.
        </p>
        <a class="btn btn-info" href="@Url.Action("Volunteer", "About")">Volunteer Info&nbsp;<i class="fa fa-group"></i></a>
    </div>
    <h1>IFC Board</h1>
    <hr />
    @for (int i = 0; i < (int)Math.Ceiling(Model.Board.Count() / (float)RowColumnsBoard); i++) {
        <div class="row">
            @foreach (Staff staff in Model.Board.Skip(i * RowColumnsBoard).Take(RowColumnsBoard)) {
                <div class="col-sm-@(12 / RowColumnsBoard) ifc-board">
                    <div class="well text-center">
                        @if (!string.IsNullOrWhiteSpace(staff.ImageUrl)) {
                            <img class="img-fullwidth staff-icon" src="@Url.Content("~/" + staff.ImageUrl)" alt="staff-img-@staff.Title">
} else {
                            <img class="img-fullwidth staff-icon" alt="staff-img-@staff.Title">
}
                        <h3>@staff.Name</h3>
                        <h4>@staff.Title</h4>
                        @if (!string.IsNullOrWhiteSpace(staff.Bio)) {
                            <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#board-@staff.Id">More Info</button>
}

                        @if (!string.IsNullOrWhiteSpace(staff.EmailAddress)) {
                            <a class="btn btn-success btn-block" href="mailto:@staff.EmailAddress">Email</a>
}

                    </div>
                </div>
}
        </div>
    }
    <h1>Staff <span>(minions)</span></h1>
    <hr />
    @for (int i = 0; i < (int)Math.Ceiling(Model.Staff.Count() / (float)RowColumnsStaff); i++) {
        <div class="row">
            @foreach (Staff staff in Model.Staff.Skip(i * RowColumnsStaff).Take(RowColumnsStaff)) {
                <div class="col-sm-@(12 / RowColumnsStaff) ifc-staff">
                    <div class="well text-center">
                        @if (!string.IsNullOrWhiteSpace(staff.ImageUrl)) {
                            <img class="img-fullwidth staff-icon" src="@Url.Content("~/" + staff.ImageUrl)" alt="staff-img-@staff.Title">
} else {
                            <img class="img-fullwidth vhs-blur-box staff-icon" src="@Url.Content("~/images/staff/nopic.jpg")" alt="staff-img-@staff.Title-no-img">
}
                        <h3>@staff.Name</h3>
                        <h4>@staff.Title</h4>
                        @if (!string.IsNullOrWhiteSpace(staff.Bio)) {
                            <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#staff-@staff.Id">More Info</button>
}

                        @if (!string.IsNullOrWhiteSpace(staff.EmailAddress)) {
                            <a class="btn btn-success btn-block" href="mailto:@staff.EmailAddress">Email</a>
}

                    </div>
                </div>
}
        </div>
    }
</div>

@foreach (Staff staff in Model.Board.Where(s => !string.IsNullOrWhiteSpace(s.Bio))) {
    <div class="modal fade" id="board-@staff.Id" tabindex="-1" role="dialog" aria-labelledby="#board-@staff.Id-label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    @*<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>*@
                    <div class="row">
                        <div class="col-md-4">
                            <img class="staff-icon" src="@Url.Content("~/" + staff.ImageUrl)" alt="staff-img-@staff.Title">
                        </div>
                        <div class="col-md-8">
                            <h1 class="modal-title" id="@staff.Id-label">@staff.Name</h1>
                            <h3 class="modal-title" id="@staff.Title-label">@staff.Title</h3>
                        </div>
                    </div>
                </div>
                <div class="modal-body">
                    <p>@Html.Raw(staff.Bio)</p>
                </div>
                <div class="modal-footer">
                    @if (!string.IsNullOrWhiteSpace(staff.EmailAddress)) {
                        <a type="button" class="btn btn-success" href="mailto:@staff.EmailAddress">Email</a>
}
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}

@foreach (Staff staff in Model.Staff.Where(s => !string.IsNullOrWhiteSpace(s.Bio))) {
    <div class="modal fade" id="staff-@staff.Id" tabindex="-1" role="dialog" aria-labelledby="#staff-@staff.Id-label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    @*<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>*@
                    <div class="row">
                        <div class="col-md-4">
                            <img class="staff-icon" src="@Url.Content("~/" + staff.ImageUrl)" alt="staff-img-@staff.Title">
                        </div>
                        <div class="col-md-8">
                            <h1 class="modal-title" id="@staff.Id-label">@staff.Name</h1>
                            <h3 class="modal-title" id="@staff.Title-label">@staff.Title</h3>
                        </div>
                    </div>
                </div>
                <div class="modal-body">
                    <p>@Html.Raw(staff.Bio)</p>
                </div>
                <div class="modal-footer">
                    @if (!string.IsNullOrWhiteSpace(staff.EmailAddress)) {
                        <a type="button" class="btn btn-success" href="mailto:@staff.EmailAddress">Email</a>
}
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}

src/IndyFurConCore/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@* Overriding the style of iframes *@
<style>
    iframe {
        width: 100% !important;
    }

    .btn-row .btn {
        font-size: 24px;
        font-family: Simpleness;
    }
</style>
<div class="container-body">
    <div class="hide-on-expand title-container">
        <img id="title-image" class="img-fullwidth" src="@Url.Content("~/images/2017_HighRes.png")">
        <h2 id="title-subtitle" class="no-margin-top">
            We <span class="glyphicon glyphicon-heart-empty"></span> the 80s!
        </h2>
    </div>
    <div class="row" id="clockRow" style="display: none;">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-body" style="text-align: center">
                    <h1 id="countdown">We &lt;3 javascript</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="well">
                <h2 class="no-margin-top">When</h2>
                <p>Fri-Sun, August 11-13, 2017</p>
                <hr />
                <h2>Where</h2>
                <p>
                    <a href="@Url.Action("Hotel", "Attend")#marriott">Indianapolis Marriott East</a>,
                    Indianapolis, IN
                </p>
                <div class="row btn-row">
                    <div class="col-md-4">
                        <a class="btn btn-info btn-block" href="https://www.google.com/maps/place/Indianapolis+Marriott+East,+7202+E+21st+St,+Indianapolis,+IN+46219" target="_blank">
                            <i class="fa fa-map"></i><br />
                            Navigation
                        </a>
                    </div>
                    <div class="col-md-4">
                        <a class="btn btn-primary btn-block" href="http://indyfurcon2017.sched.com/" target="_blank">
                            <i class="fa fa-calendar"></i><br />
                            <span>Schedule</span>
                        </a>
                    </div>
                    <div class="col-md-4">
                        <a class="btn btn-success btn-block" href="@Url.Action("Volunteer", "About")">
                            <i class="fa fa-group"></i><br />
                            <span>Volunteer</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="well">
                <div class="row guest-box">
                    <div class="col-md-12">
                        <h2>Guests of Honor</h2>
                        <hr />
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="col-md-4 img-container">
                                <img class="staff-icon" src="@Url.Content("~/images/xander-the-blue.jpg")" />
                            </div>
                            <div class="col-md-8 info-container">
                                <h3><span>Xander</span> <span>the Blue</span></h3>
                                <ul>
                                    <li>Artist</li>
                                    <li>Comedian</li>
                                    <li>Fursuiter</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="col-md-4 img-container">
                                <img class="staff-icon" src="@Url.Content("~/images/doryuu.jpg")" />
                            </div>
                            <div class="col-md-8 info-container">
                                <h3>Doryuu</h3>
                                <ul>
                                    <li>Artist</li>
                                    <li>Dancer</li>
                                    <li>Fursuiter</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12" style="font-size: 20px">
            <div class="panel panel-info">
                <div class="panel-body">
                    <p>
                        IndyFurCon 2017, <a href="about">Indiana's 8th annual</a> <a href="https://en.wikipedia.org/wiki/Furry_convention">furry convention</a>,
                        takes place Friday-Sunday, August 11-13, 2017 at the <a href="hotel">Indianapolis Marriott East</a>! iFC2017, themed
                        "We Love the 80s," welcomes guests of honor Doryuu and Xander The Blue and raises donations for
                        <a href="charity">Southside Animal Shelter</a> to rescue at-risk adoptable cats and dogs.
                    </p>
                    <p>
                        IndyFurCon thanks our 1010 attendees of iFC2016 for making our convention awesome and raising $10,286 for
                        <a href="charity">Southside Animal Shelter</a> to rescue many cats and dogs. Thank you volunteers and panelists for
                        your hard work entertaining everyone with 160 hours of programming. Thank you sponsors and super sponsors who enable
                        us to make iFC2017 even better. See you again in August!
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div id="facebook" class="col-md-6">
                    <iframe src="https://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2FIndyFurCon&amp;colorscheme=light&amp;show_faces=false&amp;stream=true&amp;header=true&amp;width=600&amp;height=600" scrolling="yes" frameborder="0" style="width: 100%; height: 600px;" allowtransparency="true"></iframe>
                </div>
                <div id="twitter" class="col-md-6">
                    <a class="twitter-timeline" href="https://twitter.com/IndyFurCon" data-widget-id="577180197528600576">Tweets by @@IndyFurCon</a>
                    <script>!function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = "https://platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs); } }(document, "script", "twitter-wjs");</script>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="screenblock" class="screen-block" style="display: none; position: fixed; left:0; right: 0; bottom: 0; top: 0; z-index: 101">
    <video loop id="vid" style="min-width: 100%; min-height: 100%">
        <source src="@Url.Content("~/videos/surprise.mp4")" type="video/mp4">
    </video>
</div>
<button id="screenblockremover" class="btn btn-block btn-danger" style="display: none; position: fixed; bottom: 10px; left: 10px; right: 20px; z-index: 1000;" onclick="removeTheSexy()">
    <h1 style="margin: 10vh 0;">
        MAKE IT STOP!!!
    </h1>
</button>

@section prenav {
    <div class="pre-nav-panel">
        <div class="content-wrapper">
            <img src="@Url.Content("~/images/Logo_2017.png")" class="ifc-logo animated fadeInUp" />
            <div class="ifc-logo-skyline animated slideInUp"></div>
        </div>
        <div class="grid animated slideInUp"></div>
        <div class="content-wrapper">
            <div class="logo-glow"></div>
            <img src="@Url.Content("~/images/buffalo.png")" class="ifc-logo-buffalo animated fadeInLeft" />
            <img src="@Url.Content("~/images/cardinal.png")" class="ifc-logo-cardinal animated fadeInRight" />
            <img src="@Url.Content("~/images/Text_2017.png")" class="ifc-logo-text animated zoomInDown" />
            <img src="@Url.Content("~/images/2017.png")" class="ifc-logo-text-year animated lightSpeedIn" />
        </div>
    </div>
}
@section scripts {
    <script src="~/lib/jquery.countdown/dist/jquery.countdown.js"></script>
    <script>
        $(document).ready(function () {
            $("#clockRow").show();
            var ceremonies = new Date(2017, 7, 11, 11, 0, 0, 0);
            //$("#countdown").countdown(new Date(2017, 7, 11, 11, 0, 0, 0))
            var now = new Date();
            var soon = now.setSeconds(now.getSeconds() + 3);

            // Are we before ceremonies
            if (ceremonies > now) {
                // Test
                //$("#countdown").countdown(soon)
                $("#countdown").countdown(ceremonies)
                    .on('update.countdown', function (e) {
                        $(this).text(e.strftime('%D:%H:%M:%S'));
                    })
                    .on('finish.countdown', function (e) {
                        var test = $("#vid").get(0);
                        test.play();
                        $('#screenblock').show();

                        if (test.requestFullScreen
                            || test.mozRequestFullScreen
                            || test.webkitRequestFullScreen
                            || test.webkitEnterFullscreen) {
                            $('#screenblockremover').delay(10000).fadeIn(1000);
                        } else {
                            // Your browser sucks
                            $('#screenblock').hide();
                            return;
                        }
                    });
            } else {
                removeTheSexy();
            }

        });

        function removeTheSexy() {
            $("#clockRow").hide();
            $('#screenblock').remove();
            $('#screenblockremover').remove();
        }

        $('#title-image').on('load', function () {
            $('#title-image').addClass("animated fadeInDown");
            $('#title-subtitle').addClass("animated fadeIn");
        });
    </script>
}

src/IndyFurConCore/Views/Shared/_Layout.cshtml
@using IndyFurConCore.Util
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, IndyFurConCore
<!DOCTYPE html>
<html lang="us-en">
<head>
    @* IE backup *@
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8"/>
    <meta name="description" content="IndyFurCon 2017, Indiana's 8th annual furry convention.</a>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - IndyFurCon</title>
    <link rel="shortcut icon" type="image/x-icon" href="@Url.Content("~/ifc.ico")"/>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css"/>
        <link rel="stylesheet" href="~/lib/animate.css/animate.css">
        <link rel="stylesheet" href="~/css/site.css"/>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css"/>
        <link rel="stylesheet" href="~/lib/animate.css/animate.min.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
    </environment>
</head>
<body>
    @RenderSection("prenav", required: false)
    <div id="navbar" class="navbar navbar-inverse @if (!IsSectionDefined("prenav")) { @Html.Raw("navbar-fixed-top") }" @if (IsSectionDefined("prenav")){ @Html.Raw("data-spy=\"affix\" data-offset-top=\"300\"") }>
        <div class="container">
            <div class="navbar-header">
                <a href="@Url.Action("Index", "Home")" class="navbar-brand ifc-logo">
                    <img src="@Url.Content("~/images/iFC Transparent Logo wht sml.png")" alt="ifc-logo-sml" />
                </a>
                @*<a href="@Url.Action("Index", "Home")" class="navbar-brand hide-on-collapse"><b>Indy</b>FurCon</a>*@
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Register", "Home")" class="electro">Register</a>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">About <span class="caret"></span></a>
                        <ul class="dropdown-menu slideInDown" role="menu">
                            <li>@Html.ActionLink("Charity", "Charity", "About")</li>
                            <li>@Html.ActionLink("Staff", "Staff", "About")</li>
                            <li>@Html.ActionLink("About IndyFurCon", "Index", "About")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Attend <span class="caret"></span></a>
                        <ul class="dropdown-menu slideInDown" role="menu">
                            <li>@Html.ActionLink("Programming", "Programming", "Attend")</li>
                            <li>@Html.ActionLink("Hotel", "Hotel", "Attend")</li>
                            <li>@Html.ActionLink("Travel", "Travel", "Attend")</li>
                            <li>@Html.ActionLink("Policies", "Index", "Policies")</li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="link-collection">
                        <a class="vhs-blur" href="https://twitter.com/IndyFurCon" alt="Twitter"><span class="fa fa-twitter"></span></a>
                        <a class="vhs-blur" href="https://www.facebook.com/IndyFurCon" alt="Facebook"><span class="fa fa-facebook-official"></span></a>
                        <a class="vhs-blur" href="https://www.youtube.com/user/TheIndyFurCon" alt="Youtube"><span class="fa fa-youtube-play"></span></a>
                        <a class="vhs-blur" href="https://www.furaffinity.net/user/IndyFurCon" alt="FurAffinity"><span class="fa fa-paw"></span></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <footer class="container body-content">
        <hr />
        <p>&copy; 2017 - IndyFurCon/Con Glomerate</p>
    </footer>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>